//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWin_FE.FEBata {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.online.asp.core.paperless.cl", ConfigurationName="FEBata.OnlinePortType")]
    public interface OnlinePortType {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:CargaInformeBajas", ReplyAction="urn:CargaInformeBajasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.CargaInformeBajasResponse CargaInformeBajas(ServiceWin_FE.FEBata.CargaInformeBajasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GenInformeReversiones", ReplyAction="urn:GenInformeReversionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.GenInformeReversionesResponse GenInformeReversiones(ServiceWin_FE.FEBata.GenInformeReversionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineConsultaEstado", ReplyAction="urn:OnlineConsultaEstadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.OnlineConsultaEstadoResponse OnlineConsultaEstado(ServiceWin_FE.FEBata.OnlineConsultaEstadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRecList", ReplyAction="urn:OnlineRecoveryRecListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.OnlineRecoveryRecListResponse OnlineRecoveryRecList(ServiceWin_FE.FEBata.OnlineRecoveryRecListRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Consult", ReplyAction="urn:ConsultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.ConsultResponse Consult(ServiceWin_FE.FEBata.ConsultRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConsultaInformeReversiones", ReplyAction="urn:ConsultaInformeReversionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.ConsultaInformeReversionesResponse ConsultaInformeReversiones(ServiceWin_FE.FEBata.ConsultaInformeReversionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecovery", ReplyAction="urn:OnlineRecoveryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.OnlineRecoveryResponse OnlineRecovery(ServiceWin_FE.FEBata.OnlineRecoveryRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineARC", ReplyAction="urn:OnlineARCResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.OnlineARCResponse OnlineARC(ServiceWin_FE.FEBata.OnlineARCRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:AddDocInfo", ReplyAction="urn:AddDocInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.AddDocInfoResponse AddDocInfo(ServiceWin_FE.FEBata.AddDocInfoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarAdjuntosRecibidos", ReplyAction="urn:listarAdjuntosRecibidosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.listarAdjuntosRecibidosResponse listarAdjuntosRecibidos(ServiceWin_FE.FEBata.listarAdjuntosRecibidosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:InformeResBoletasDiario", ReplyAction="urn:InformeResBoletasDiarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.InformeResBoletasDiarioResponse InformeResBoletasDiario(ServiceWin_FE.FEBata.InformeResBoletasDiarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGeneration", ReplyAction="urn:OnlineGenerationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.OnlineGenerationResponse OnlineGeneration(ServiceWin_FE.FEBata.OnlineGenerationRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineEventos", ReplyAction="urn:OnlineEventosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.OnlineEventosResponse OnlineEventos(ServiceWin_FE.FEBata.OnlineEventosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRec", ReplyAction="urn:OnlineRecoveryRecResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceWin_FE.FEBata.OnlineRecoveryRecResponse OnlineRecoveryRec(ServiceWin_FE.FEBata.OnlineRecoveryRecRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargaInformeBajas", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class CargaInformeBajasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docTxt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string periodo;
        
        public CargaInformeBajasRequest() {
        }
        
        public CargaInformeBajasRequest(string ruc, string login, string clave, string docTxt, string periodo) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.docTxt = docTxt;
            this.periodo = periodo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargaInformeBajasResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class CargaInformeBajasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public CargaInformeBajasResponse() {
        }
        
        public CargaInformeBajasResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenInformeReversiones", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class GenInformeReversionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        public int tpoGen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tramaTxt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string periodo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=6)]
        public bool envioSUNAT;
        
        public GenInformeReversionesRequest() {
        }
        
        public GenInformeReversionesRequest(string ruc, string login, string clave, int tpoGen, string tramaTxt, string periodo, bool envioSUNAT) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.tpoGen = tpoGen;
            this.tramaTxt = tramaTxt;
            this.periodo = periodo;
            this.envioSUNAT = envioSUNAT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenInformeReversionesResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class GenInformeReversionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public GenInformeReversionesResponse() {
        }
        
        public GenInformeReversionesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineConsultaEstado", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineConsultaEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rucReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=6)]
        public int estado;
        
        public OnlineConsultaEstadoRequest() {
        }
        
        public OnlineConsultaEstadoRequest(string ruc, string login, string clave, string rucReceptor, string fechaInicio, string fechaFin, int estado) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.rucReceptor = rucReceptor;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineConsultaEstadoResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineConsultaEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineConsultaEstadoResponse() {
        }
        
        public OnlineConsultaEstadoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecList", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fecha;
        
        public OnlineRecoveryRecListRequest() {
        }
        
        public OnlineRecoveryRecListRequest(string ruc, string login, string clave, string fecha) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecListResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineRecoveryRecListResponse() {
        }
        
        public OnlineRecoveryRecListResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Consult", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class ConsultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @params;
        
        public ConsultRequest() {
        }
        
        public ConsultRequest(string ruc, string login, string clave, string @params) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.@params = @params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class ConsultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public ConsultResponse() {
        }
        
        public ConsultResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformeReversiones", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class ConsultaInformeReversionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        public int idRegistro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numTicketSunat;
        
        public ConsultaInformeReversionesRequest() {
        }
        
        public ConsultaInformeReversionesRequest(string ruc, string login, string clave, int idRegistro, string numTicketSunat) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.idRegistro = idRegistro;
            this.numTicketSunat = numTicketSunat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformeReversionesResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class ConsultaInformeReversionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public ConsultaInformeReversionesResponse() {
        }
        
        public ConsultaInformeReversionesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecovery", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        public int tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        public int tipoRetorno;
        
        public OnlineRecoveryRequest() {
        }
        
        public OnlineRecoveryRequest(string ruc, string login, string clave, int tipoDoc, string folio, int tipoRetorno) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.tipoDoc = tipoDoc;
            this.folio = folio;
            this.tipoRetorno = tipoRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineRecoveryResponse() {
        }
        
        public OnlineRecoveryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineARC", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineARCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rucEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        public int tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=6)]
        public int estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version;
        
        public OnlineARCRequest() {
        }
        
        public OnlineARCRequest(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int estado, string version) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.rucEmisor = rucEmisor;
            this.tipoDoc = tipoDoc;
            this.folio = folio;
            this.estado = estado;
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineARCResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineARCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineARCResponse() {
        }
        
        public OnlineARCResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDocInfo", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class AddDocInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        public int tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string infoAdicional;
        
        public AddDocInfoRequest() {
        }
        
        public AddDocInfoRequest(string ruc, string login, string clave, int tipoDoc, string folio, string infoAdicional) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.tipoDoc = tipoDoc;
            this.folio = folio;
            this.infoAdicional = infoAdicional;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDocInfoResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class AddDocInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public AddDocInfoResponse() {
        }
        
        public AddDocInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAdjuntosRecibidos", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class listarAdjuntosRecibidosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rucEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        public int tipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        public listarAdjuntosRecibidosRequest() {
        }
        
        public listarAdjuntosRecibidosRequest(string ruc, string login, string clave, string rucEmisor, int tipoDocumento, string folio) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.rucEmisor = rucEmisor;
            this.tipoDocumento = tipoDocumento;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAdjuntosRecibidosResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class listarAdjuntosRecibidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public listarAdjuntosRecibidosResponse() {
        }
        
        public listarAdjuntosRecibidosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InformeResBoletasDiario", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class InformeResBoletasDiarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fechaInforme;
        
        public InformeResBoletasDiarioRequest() {
        }
        
        public InformeResBoletasDiarioRequest(string ruc, string login, string clave, string fechaInforme) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.fechaInforme = fechaInforme;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InformeResBoletasDiarioResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class InformeResBoletasDiarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public InformeResBoletasDiarioResponse() {
        }
        
        public InformeResBoletasDiarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGeneration", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docTxt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        public int tipoFoliacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        public int tipoRetorno;
        
        public OnlineGenerationRequest() {
        }
        
        public OnlineGenerationRequest(string ruc, string login, string clave, string docTxt, int tipoFoliacion, int tipoRetorno) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.docTxt = docTxt;
            this.tipoFoliacion = tipoFoliacion;
            this.tipoRetorno = tipoRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineGenerationResponse() {
        }
        
        public OnlineGenerationResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineEventos", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineEventosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docTxt;
        
        public OnlineEventosRequest() {
        }
        
        public OnlineEventosRequest(string ruc, string login, string clave, string docTxt) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.docTxt = docTxt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineEventosResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineEventosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineEventosResponse() {
        }
        
        public OnlineEventosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRec", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rucEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        public int tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=6)]
        public int tipoRetorno;
        
        public OnlineRecoveryRecRequest() {
        }
        
        public OnlineRecoveryRecRequest(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int tipoRetorno) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.rucEmisor = rucEmisor;
            this.tipoDoc = tipoDoc;
            this.folio = folio;
            this.tipoRetorno = tipoRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineRecoveryRecResponse() {
        }
        
        public OnlineRecoveryRecResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OnlinePortTypeChannel : ServiceWin_FE.FEBata.OnlinePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlinePortTypeClient : System.ServiceModel.ClientBase<ServiceWin_FE.FEBata.OnlinePortType>, ServiceWin_FE.FEBata.OnlinePortType {
        
        public OnlinePortTypeClient() {
        }
        
        public OnlinePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlinePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlinePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlinePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.CargaInformeBajasResponse ServiceWin_FE.FEBata.OnlinePortType.CargaInformeBajas(ServiceWin_FE.FEBata.CargaInformeBajasRequest request) {
            return base.Channel.CargaInformeBajas(request);
        }
        
        public string CargaInformeBajas(string ruc, string login, string clave, string docTxt, string periodo) {
            ServiceWin_FE.FEBata.CargaInformeBajasRequest inValue = new ServiceWin_FE.FEBata.CargaInformeBajasRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            inValue.periodo = periodo;
            ServiceWin_FE.FEBata.CargaInformeBajasResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).CargaInformeBajas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.GenInformeReversionesResponse ServiceWin_FE.FEBata.OnlinePortType.GenInformeReversiones(ServiceWin_FE.FEBata.GenInformeReversionesRequest request) {
            return base.Channel.GenInformeReversiones(request);
        }
        
        public string GenInformeReversiones(string ruc, string login, string clave, int tpoGen, string tramaTxt, string periodo, bool envioSUNAT) {
            ServiceWin_FE.FEBata.GenInformeReversionesRequest inValue = new ServiceWin_FE.FEBata.GenInformeReversionesRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tpoGen = tpoGen;
            inValue.tramaTxt = tramaTxt;
            inValue.periodo = periodo;
            inValue.envioSUNAT = envioSUNAT;
            ServiceWin_FE.FEBata.GenInformeReversionesResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).GenInformeReversiones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.OnlineConsultaEstadoResponse ServiceWin_FE.FEBata.OnlinePortType.OnlineConsultaEstado(ServiceWin_FE.FEBata.OnlineConsultaEstadoRequest request) {
            return base.Channel.OnlineConsultaEstado(request);
        }
        
        public string OnlineConsultaEstado(string ruc, string login, string clave, string rucReceptor, string fechaInicio, string fechaFin, int estado) {
            ServiceWin_FE.FEBata.OnlineConsultaEstadoRequest inValue = new ServiceWin_FE.FEBata.OnlineConsultaEstadoRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucReceptor = rucReceptor;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            inValue.estado = estado;
            ServiceWin_FE.FEBata.OnlineConsultaEstadoResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).OnlineConsultaEstado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.OnlineRecoveryRecListResponse ServiceWin_FE.FEBata.OnlinePortType.OnlineRecoveryRecList(ServiceWin_FE.FEBata.OnlineRecoveryRecListRequest request) {
            return base.Channel.OnlineRecoveryRecList(request);
        }
        
        public string OnlineRecoveryRecList(string ruc, string login, string clave, string fecha) {
            ServiceWin_FE.FEBata.OnlineRecoveryRecListRequest inValue = new ServiceWin_FE.FEBata.OnlineRecoveryRecListRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.fecha = fecha;
            ServiceWin_FE.FEBata.OnlineRecoveryRecListResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).OnlineRecoveryRecList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.ConsultResponse ServiceWin_FE.FEBata.OnlinePortType.Consult(ServiceWin_FE.FEBata.ConsultRequest request) {
            return base.Channel.Consult(request);
        }
        
        public string Consult(string ruc, string login, string clave, string @params) {
            ServiceWin_FE.FEBata.ConsultRequest inValue = new ServiceWin_FE.FEBata.ConsultRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.@params = @params;
            ServiceWin_FE.FEBata.ConsultResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).Consult(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.ConsultaInformeReversionesResponse ServiceWin_FE.FEBata.OnlinePortType.ConsultaInformeReversiones(ServiceWin_FE.FEBata.ConsultaInformeReversionesRequest request) {
            return base.Channel.ConsultaInformeReversiones(request);
        }
        
        public string ConsultaInformeReversiones(string ruc, string login, string clave, int idRegistro, string numTicketSunat) {
            ServiceWin_FE.FEBata.ConsultaInformeReversionesRequest inValue = new ServiceWin_FE.FEBata.ConsultaInformeReversionesRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.idRegistro = idRegistro;
            inValue.numTicketSunat = numTicketSunat;
            ServiceWin_FE.FEBata.ConsultaInformeReversionesResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).ConsultaInformeReversiones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.OnlineRecoveryResponse ServiceWin_FE.FEBata.OnlinePortType.OnlineRecovery(ServiceWin_FE.FEBata.OnlineRecoveryRequest request) {
            return base.Channel.OnlineRecovery(request);
        }
        
        public string OnlineRecovery(string ruc, string login, string clave, int tipoDoc, string folio, int tipoRetorno) {
            ServiceWin_FE.FEBata.OnlineRecoveryRequest inValue = new ServiceWin_FE.FEBata.OnlineRecoveryRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.tipoRetorno = tipoRetorno;
            ServiceWin_FE.FEBata.OnlineRecoveryResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).OnlineRecovery(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.OnlineARCResponse ServiceWin_FE.FEBata.OnlinePortType.OnlineARC(ServiceWin_FE.FEBata.OnlineARCRequest request) {
            return base.Channel.OnlineARC(request);
        }
        
        public string OnlineARC(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int estado, string version) {
            ServiceWin_FE.FEBata.OnlineARCRequest inValue = new ServiceWin_FE.FEBata.OnlineARCRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.estado = estado;
            inValue.version = version;
            ServiceWin_FE.FEBata.OnlineARCResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).OnlineARC(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.AddDocInfoResponse ServiceWin_FE.FEBata.OnlinePortType.AddDocInfo(ServiceWin_FE.FEBata.AddDocInfoRequest request) {
            return base.Channel.AddDocInfo(request);
        }
        
        public string AddDocInfo(string ruc, string login, string clave, int tipoDoc, string folio, string infoAdicional) {
            ServiceWin_FE.FEBata.AddDocInfoRequest inValue = new ServiceWin_FE.FEBata.AddDocInfoRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.infoAdicional = infoAdicional;
            ServiceWin_FE.FEBata.AddDocInfoResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).AddDocInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.listarAdjuntosRecibidosResponse ServiceWin_FE.FEBata.OnlinePortType.listarAdjuntosRecibidos(ServiceWin_FE.FEBata.listarAdjuntosRecibidosRequest request) {
            return base.Channel.listarAdjuntosRecibidos(request);
        }
        
        public string listarAdjuntosRecibidos(string ruc, string login, string clave, string rucEmisor, int tipoDocumento, string folio) {
            ServiceWin_FE.FEBata.listarAdjuntosRecibidosRequest inValue = new ServiceWin_FE.FEBata.listarAdjuntosRecibidosRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDocumento = tipoDocumento;
            inValue.folio = folio;
            ServiceWin_FE.FEBata.listarAdjuntosRecibidosResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).listarAdjuntosRecibidos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.InformeResBoletasDiarioResponse ServiceWin_FE.FEBata.OnlinePortType.InformeResBoletasDiario(ServiceWin_FE.FEBata.InformeResBoletasDiarioRequest request) {
            return base.Channel.InformeResBoletasDiario(request);
        }
        
        public string InformeResBoletasDiario(string ruc, string login, string clave, string fechaInforme) {
            ServiceWin_FE.FEBata.InformeResBoletasDiarioRequest inValue = new ServiceWin_FE.FEBata.InformeResBoletasDiarioRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.fechaInforme = fechaInforme;
            ServiceWin_FE.FEBata.InformeResBoletasDiarioResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).InformeResBoletasDiario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.OnlineGenerationResponse ServiceWin_FE.FEBata.OnlinePortType.OnlineGeneration(ServiceWin_FE.FEBata.OnlineGenerationRequest request) {
            return base.Channel.OnlineGeneration(request);
        }
        
        public string OnlineGeneration(string ruc, string login, string clave, string docTxt, int tipoFoliacion, int tipoRetorno) {
            ServiceWin_FE.FEBata.OnlineGenerationRequest inValue = new ServiceWin_FE.FEBata.OnlineGenerationRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            inValue.tipoFoliacion = tipoFoliacion;
            inValue.tipoRetorno = tipoRetorno;
            ServiceWin_FE.FEBata.OnlineGenerationResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).OnlineGeneration(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.OnlineEventosResponse ServiceWin_FE.FEBata.OnlinePortType.OnlineEventos(ServiceWin_FE.FEBata.OnlineEventosRequest request) {
            return base.Channel.OnlineEventos(request);
        }
        
        public string OnlineEventos(string ruc, string login, string clave, string docTxt) {
            ServiceWin_FE.FEBata.OnlineEventosRequest inValue = new ServiceWin_FE.FEBata.OnlineEventosRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            ServiceWin_FE.FEBata.OnlineEventosResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).OnlineEventos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWin_FE.FEBata.OnlineRecoveryRecResponse ServiceWin_FE.FEBata.OnlinePortType.OnlineRecoveryRec(ServiceWin_FE.FEBata.OnlineRecoveryRecRequest request) {
            return base.Channel.OnlineRecoveryRec(request);
        }
        
        public string OnlineRecoveryRec(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int tipoRetorno) {
            ServiceWin_FE.FEBata.OnlineRecoveryRecRequest inValue = new ServiceWin_FE.FEBata.OnlineRecoveryRecRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.tipoRetorno = tipoRetorno;
            ServiceWin_FE.FEBata.OnlineRecoveryRecResponse retVal = ((ServiceWin_FE.FEBata.OnlinePortType)(this)).OnlineRecoveryRec(inValue);
            return retVal.@return;
        }
    }
}
